name: API Tests Karate

on:
  workflow_dispatch:
  push:
    branches: [ karate, main ]
  pull_request:
    branches: [ karate, main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Configurar Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Instalar dependencias
        run: mvn clean install

      - name: Ejecutar pruebas Karate
        run: mvn test -Dkarate.env="certificacion"
